### ISSUE TITLE
Non-sensible conversion due to context negligence

### ISSUE THREAD

**Issue by xuancong84** [berniey/hanziconv#7]
Converting traditional Chinese characters into simplified Chinese characters is NEVER as simple as UTF-8 character replacement. In fact, there is a list of words that need to be preserved, otherwise, 乾隆 will become 干隆, 乾坤 will become 干坤, which becomes non-sense after your toolkit conversion.

In fact, how certain characters convert will depend on its context which you cannot ignore.

Moreover, your character table is not complete, 蹻 (跷) is not converted either.

Try to compare with the other toolkit called mafan (https://github.com/hermanschaaf/mafan) and complement your conversion table.

**Comment by berniey** [comment]
irrelevant

**Comment by xuancong84** [comment]
It is relevant. I guess you don't know Chinese. Do you know what 乾隆 means?
